arch:
  - amd64
  - ppc64le
language: node_js

sudo: false

node_js:
  - "14"
  - "13"
  - "12"
  - "11"
  - "10"
  - "8"

script:
  - npm test
  - if [[ ${TRAVIS_NODE_VERSION} == "8" ]]; then npm run coverage; fi;
